name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - run: go build -ldflags "-s -w -X deploycli/internal/static.Version=${{ github.ref_name }}" -o deploycli .

      - run: sudo apt install -y upx && upx --best deploycli

      - uses: softprops/action-gh-release@v2
        with:
          files: deploycli
