name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - run: go build -ldflags "-X deploycli/internal/static.Version=${{ github.ref_name }}" -o deploycli .

      - uses: actions/upload-artifact@v4
        with:
          name: deploycli-${{ github.ref_name }}
          path: deploycli
